courier_salary_calculator:
  cron: "0 8 * * *"
  class: "CourierSalaryJob"
  queue: default

pg_hero_stats:
  cron: "*/5 * * * *"
  class: "PgHero::StatsJob"
  queue: pg_hero

pg_hero_space:
  cron: "10 0 * * *"
  class: "PgHero::SpaceJob"
  queue: pg_hero
